version: "3.9"

services:
  application:
    network_mode: host
    stdin_open: true   # -i docker
    build:
      context: .
      dockerfile: .dockerfile
    #expose:
    #  - 8080
    ports:
      - "${shortUrlPort}:8080"
    depends_on:
      postgresdb:
        condition: service_healthy
      mysqldb:
        condition: service_healthy

  postgresdb:
    image: postgres:15.2
    restart: always
    container_name: postgres-shortener
    env_file:
      - postgres.env
    volumes:
      - "postgres_vol:/var/lib/postgres"
    #ports:
    #  - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10

  mysqldb:
    image: mysql:8
    restart: always
    container_name: mysql-shortener
    env_file:
      - mysql.env
    volumes:
      - "mysql_vol:/var/lib/mysql"
    #ports:
    #  - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

volumes:
  postgres_vol:
    external: false
  mysql_vol:
    external: false
